((nil . ((c-c++-enable-clang-format-on-save . nil)
         (clang-company-arguments . "-std=c++11")
         (compile-command . "make")
         (fill-column . 80)
         (flycheck-clang-language-standard . "-std=c++11")
         (flycheck-gcc-language-standard . "-std=c++11")
         (helm-make-arguments . "-j4")
         (indent-tabs-mode . nil)
         (tab-width . 4)))
 (makefile-automake-mode . ((indent-tabs-mode . t)))
 (c-mode . ((c-basic-offset . 4)
            (c-file-style . "BSD")))
 (c++-mode . ((c-basic-offset . 4)
              (c-file-style . "BSD")))
 (python-mode . ((python-enable-yapf-format-on-save . nil)))
 )
